import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className={'text-blue-500'}>Pikasso SDK</span>
        </h1>

        <p className={styles.description}>
          A example with Next.js{' '}
          <Link href={'/nfts/[nfts]'} as={`/nfts/1001`}>
            {' '}
            <code className={styles.code}>pages/nfts/[nftId]/index.tsx</code>
          </Link>
        </p>
      </main>

      <iframe
        width="100%"
        height="710"
        src="http://localhost:3000/embed/list-collection/2e867790-0691-4900-98ad-3f2b40e4d7cc"
      ></iframe>
    </div>
  );
};

export default Home;
